NDefines.NGame.END_DATE = "2000.1.1.1";
NDefines.NCountry.RADAR_RANGE_MAX = 400;

NDefines.NAir.AIR_WING_MAX_STATS_ATTACK = 200000;
NDefines.NAir.AIR_WING_MAX_STATS_DEFENCE = 200000;
NDefines.NAir.AIR_WING_MAX_STATS_AGILITY = 200000;
NDefines.NAir.AIR_WING_MAX_STATS_SPEED = 80000000;
NDefines.NAir.AIR_WING_MAX_STATS_BOMBING = 200000;
NDefines.NAir.DETECT_CHANCE_FROM_RADARS = 0.75;
NDefines.NAir.DETECT_EFFICIENCY_FROM_RADAR = 0.75;

NDefines.NAI.WANTED_CARRIER_PLANES_PER_CARRIER_CAPACITY_FACTOR = 1;
NDefines.NAI.FIX_SUPPLY_BOTTLENECK_SATURATION_THRESHOLD = 0.75;